W6D5/ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  
end

W6D5/ninety_nine_cats/app/models/cat.rb
class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper
  COLORS = ['Black', 'White', 'Grey', 'Brown', 'Orange']
  SEX = ['M', 'F']

  validates :color, inclusion: COLORS
  validates :sex, inclusion: SEX
  validates :name, :color, :sex, :description, :birth_date, presence: true

  def age
    time_ago_in_words(birth_date)
  end

  def self.colors
    COLORS
  end
end

W6D5/ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

W6D5/ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all
        render 'index'
    end

    def show
        @cat = Cat.find_by(id:params[:id])
        if @cat
            render :show
        else
            redirect_to cats_url
        end
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            redirect_to cats_url
        else
            redirect_to new_cat_url
        end
    end

    def edit
      @cat = Cat.find(params[:id])
      render :edit
    end

    def update
      @cat = Cat.find(params[:id])
      if @cat.update(cat_params)
        redirect_to cats_url
      else
        render json: @cat.errors.full_messages, status: 422
      end
    end

    private
    def cat_params
        params.require(:cat).permit(:name, :color, :birth_date, :sex, :description)
    end
end

W6D5/ninety_nine_cats/app/views/cats/edit.html.erb
<h1> Edit <%= @cat.name %>! </h1>


<form action='/cats' method='POST'>
<input type= 'hidden' name= _method value= 'PATCH'>

  <label for='name'>Name</label>
  <input id='name' type='text' name='cat[name]' value=' <%= @cat.name %>'>

  <br>
  <br>

  <label for='female'>Female</label>
  <input id='female' type='radio' name='cat[sex]' value= 'F' <%= @cat.sex == 'M' ? '' : 'checked' %>>
  <label for='male'>Male</label>
  <input id='male' type='radio' name='cat[sex]' value='M'<%= @cat.sex == 'F' ? '' : 'checked' %>>


  <br>
  <br>

    <select id="color" name="cat[color]">
    <option disabled >-- please select --</option>
    <% Cat.colors.each do |color| %>
        <option value= <%= color %> <%= @cat.color == color ? 'selected' : ''%>> <%= color %> </option>
    <% end %>
    </select>

    <br>
    <br>

    <label for='birth_date'>Birth Date</label>

    <br>

    <input type='date' id='birth_date' name='cat[birth_date]'>

    <br>
    <br>

    <label for='description'>Description</label>

    <br>
    
    <textarea name='cat[description]'><%= @cat.description %></textarea>

    <br>
    <br>

  <input type='submit' value='Create new cat'>
</form>

W6D5/ninety_nine_cats/app/views/cats/index.html.erb
<h1> This is all the cats! </h1>

<ul>
  <% @cats.each do |cat| %>
    <li>
      <a href='<%= cat_url(cat) %>'><%= cat.name %></a>
      
    </li>
  <% end %> 
</ul>

W6D5/ninety_nine_cats/app/views/cats/new.html.erb
<h1> Create a new cat! </h1>


<form action='/cats' method='POST'>
  <label for='name'>Name</label>
  <input id='name' type='text' name='cat[name]'>

  <br>
  <br>

  <label for='female'>Female</label>
  <input id='female' type='radio' name='cat[sex]'>
  <label for='male'>Male</label>
  <input id='male' type='radio' name='cat[sex]'>

  <br>
  <br>

    <select id="color" name="cat[color]">
    <option disabled selected>-- please select --</option>
    <% Cat.colors.each do |color| %>
        <option value= <%= color %>> <%= color %> </option>
    <% end %>
    </select>

    <br>
    <br>

    <label for='birth_date'>Birth Date</label>

    <br>

    <input type='date' id='birth_date' name='cat[birth_date]'>

    <br>
    <br>

    <label for='description'>Description</label>

    <br>
    
    <textarea name='cat[description]'><%= @cat.description%></textarea>

    <br>
    <br>

  <input type='submit' value='Create new cat'>
</form>

W6D5/ninety_nine_cats/app/views/cats/show.html.erb
<h1> This is a particular cat! </h1>

<table>
    <thead>
        <tr>
            <th colspan="4"><%= @cat.name %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>birth_date: <%= @cat.birth_date %></td>
            <td>color: <%= @cat.color %></td>
            <td>sex: <%= @cat.sex %></td>
            <td>description: <%= @cat.description %></td>
        </tr>
    </tbody>
</table>